"""Initial

Revision ID: 56777933cebe
Revises: 
Create Date: 2024-03-16 21:38:32.996397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56777933cebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username')),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_id'), 'user', ['id'], unique=False, schema='public')
    op.create_table('order',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'failed', 'pending', name='orderenum', schema='public', inherit_schema=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['public.user.id'], name=op.f('fk_order_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    schema='public'
    )
    op.create_index(op.f('ix_public_order_id'), 'order', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_order_id'), table_name='order', schema='public')
    op.drop_table('order', schema='public')
    op.drop_index(op.f('ix_public_user_id'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    # ### end Alembic commands ###
