"""Initial

Revision ID: bd3793444ff7
Revises: 
Create Date: 2024-03-16 11:51:43.404016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3793444ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('diar_text', sa.Text(), nullable=True),
    sa.Column('fixed_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record')),
    schema='public'
    )
    op.create_index(op.f('ix_public_record_id'), 'record', ['id'], unique=False, schema='public')
    op.create_table('user',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username')),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_id'), 'user', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_id'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    op.drop_index(op.f('ix_public_record_id'), table_name='record', schema='public')
    op.drop_table('record', schema='public')
    # ### end Alembic commands ###
